"""initial schema

Revision ID: 5d423d02b247
Revises: 
Create Date: 2026-03-12 10:36:58.031804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d423d02b247'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('email_addresses', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('telegram_handles', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('campaigns',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_brand', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.String(length=32), nullable=True),
    sa.Column('end_date', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_campaigns_target_brand'), 'campaigns', ['target_brand'], unique=False)
    op.create_table('feed_entries',
    sa.Column('source', sa.Enum('PHISHTANK', 'URLHAUS', 'OPENPHISH', 'CERTSTREAM', 'MANUAL', name='feedsource'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_brand', sa.String(length=255), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_entries_is_processed'), 'feed_entries', ['is_processed'], unique=False)
    op.create_index(op.f('ix_feed_entries_source'), 'feed_entries', ['source'], unique=False)
    op.create_index('ix_feed_entries_source_external_id', 'feed_entries', ['source', 'external_id'], unique=True)
    op.create_index('ix_feed_entries_url', 'feed_entries', ['url'], unique=False)
    op.create_table('campaign_actors',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'actor_id')
    )
    op.create_table('kits',
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_feed', sa.String(length=50), nullable=True),
    sa.Column('feed_entry_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.Column('sha1', sa.String(length=40), nullable=True),
    sa.Column('tlsh', sa.String(length=72), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DOWNLOADING', 'DOWNLOADED', 'ANALYZING', 'ANALYZED', 'FAILED', name='kitstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_entry_id'], ['feed_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kits_created_at', 'kits', ['created_at'], unique=False)
    op.create_index(op.f('ix_kits_sha256'), 'kits', ['sha256'], unique=True)
    op.create_index(op.f('ix_kits_source_url'), 'kits', ['source_url'], unique=False)
    op.create_index(op.f('ix_kits_status'), 'kits', ['status'], unique=False)
    op.create_index(op.f('ix_kits_tlsh'), 'kits', ['tlsh'], unique=False)
    op.create_index('ix_kits_tlsh_status', 'kits', ['tlsh', 'status'], unique=False)
    op.create_table('analysis_results',
    sa.Column('kit_id', sa.UUID(), nullable=False),
    sa.Column('analysis_type', sa.Enum('HASH', 'IOC_EXTRACTION', 'DEOBFUSCATION', 'YARA_SCAN', 'SIMILARITY', name='analysistype'), nullable=False),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('files_processed', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_kit_id'), 'analysis_results', ['kit_id'], unique=False)
    op.create_table('campaign_kits',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('kit_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'kit_id')
    )
    op.create_table('indicators',
    sa.Column('type', sa.Enum('EMAIL', 'TELEGRAM_BOT_TOKEN', 'TELEGRAM_CHAT_ID', 'C2_URL', 'IP_ADDRESS', 'SMTP_CREDENTIAL', 'BASE64_BLOCK', 'DOMAIN', 'PHONE_NUMBER', 'CRYPTOCURRENCY_WALLET', name='indicatortype'), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('kit_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicators_kit_id'), 'indicators', ['kit_id'], unique=False)
    op.create_index('ix_indicators_kit_type', 'indicators', ['kit_id', 'type'], unique=False)
    op.create_index(op.f('ix_indicators_type'), 'indicators', ['type'], unique=False)
    op.create_index('ix_indicators_type_value', 'indicators', ['type', 'value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_indicators_type_value', table_name='indicators')
    op.drop_index(op.f('ix_indicators_type'), table_name='indicators')
    op.drop_index('ix_indicators_kit_type', table_name='indicators')
    op.drop_index(op.f('ix_indicators_kit_id'), table_name='indicators')
    op.drop_table('indicators')
    op.drop_table('campaign_kits')
    op.drop_index(op.f('ix_analysis_results_kit_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index('ix_kits_tlsh_status', table_name='kits')
    op.drop_index(op.f('ix_kits_tlsh'), table_name='kits')
    op.drop_index(op.f('ix_kits_status'), table_name='kits')
    op.drop_index(op.f('ix_kits_source_url'), table_name='kits')
    op.drop_index(op.f('ix_kits_sha256'), table_name='kits')
    op.drop_index('ix_kits_created_at', table_name='kits')
    op.drop_table('kits')
    op.drop_table('campaign_actors')
    op.drop_index('ix_feed_entries_url', table_name='feed_entries')
    op.drop_index('ix_feed_entries_source_external_id', table_name='feed_entries')
    op.drop_index(op.f('ix_feed_entries_source'), table_name='feed_entries')
    op.drop_index(op.f('ix_feed_entries_is_processed'), table_name='feed_entries')
    op.drop_table('feed_entries')
    op.drop_index(op.f('ix_campaigns_target_brand'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_table('actors')
    # ### end Alembic commands ###
