"""AuditLog — append-only request journal.

Every authenticated request writes one row.  Requests in
``auth_mode='disabled'`` (community / local-eval mode) also write rows,
with ``actor_subject`` left NULL — so even a deployment running with
auth off has a full request audit trail.

Why a Postgres table instead of CloudWatch / S3 for v1:

* Queryable from the existing ``darla-admin`` CLI without leaving the
  container ("who looked at victims for kit X last week").
* Joins cleanly to ``users`` for display-name resolution.
* No new infrastructure dependency to set up.

Trade-off accepted: at ~1 row per request, this table will grow.
Retention is currently a hand-wave — drop partitions older than 1 year.
A real partitioning + compliance-driven retention number is a Phase 9+
problem (see RFC §15 Open Questions).

Sensitive-route reads (Victim PII, MonitoredDomain config) populate the
``extra`` JSONB blob with the IDs returned, so a "show me everyone who
queried Victim X" report is one indexed query.

See ``RFC 0001`` in the deployment repo for the full rationale.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from sqlalchemy import JSON, DateTime, Index, Integer, String, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from darla.models.base import Base, UUIDPrimaryKeyMixin


# JSONB in Postgres (operator support, GIN indexes); JSON on SQLite so
# in-memory unit tests against this schema can use ``create_all`` without
# pulling in a Postgres dependency.  Production always sees JSONB; the
# fallback is purely a test-harness convenience.
_JSONB_OR_JSON = JSONB().with_variant(JSON(), "sqlite")


# String constants instead of an Enum so we can add new modes (e.g.
# 'service_account', 'pat') without an enum migration.  The expected
# values today are:
#
#   'oidc'     — request authenticated by a validated OIDC JWT
#   'disabled' — request served in auth-disabled mode (community / local
#                eval); ``actor_subject`` will be NULL
#
AUTH_MODE_OIDC = "oidc"
AUTH_MODE_DISABLED = "disabled"


class AuditLog(UUIDPrimaryKeyMixin, Base):
    __tablename__ = "audit_log"

    # Wall-clock receipt time, NOT request-finish time.  Indexed because
    # 99% of audit queries are time-bounded ("last 24h", "since 7d").
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )

    # OIDC subject of the requesting user — NULL when ``auth_mode``
    # is ``'disabled'`` or for unauthenticated rejections (401 before
    # subject extraction).  Indexed for "all activity by user X".
    # NOT a foreign key to ``users.id`` because we want the row to
    # survive user deletion (audit must be tamper-evident, including
    # against accidental user-row deletes).
    actor_subject: Mapped[str | None] = mapped_column(
        String(128), nullable=True, index=True,
    )

    # Snapshot of the user's UPN at request time so audit reports
    # render without a join even after the user is gone.
    actor_upn: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # ``'oidc'`` | ``'disabled'`` (see module-level constants).
    # Plain string, not an enum, so we can introduce additional modes
    # without a schema migration.
    auth_mode: Mapped[str] = mapped_column(String(16), nullable=False)

    # HTTP method (GET, POST, PUT, DELETE, PATCH) — 8 chars covers
    # everything in IANA's registry with room to spare.
    method: Mapped[str] = mapped_column(String(8), nullable=False)

    # Request path (no query string — query params can contain PII and
    # secrets we don't want in the audit log; method+path is the
    # auditable verb).  Indexed because path-prefix filtering ("show
    # all victim accesses") is the second most common audit query
    # after time range.
    path: Mapped[str] = mapped_column(String(512), nullable=False, index=True)

    status_code: Mapped[int] = mapped_column(Integer, nullable=False)

    # End-to-end response latency in milliseconds.  Useful for spotting
    # auth-related performance regressions (JWKS cache misses, slow
    # role lookups) without standing up a separate APM stack.
    response_ms: Mapped[int] = mapped_column(Integer, nullable=False)

    # Per-request UUID generated by an upstream middleware so a single
    # request can be traced across logs + audit_log + downstream
    # systems.  Also surfaced in error responses for support flows.
    request_id: Mapped[str] = mapped_column(String(64), nullable=False)

    # Free-form JSONB for route-specific audit data.  Today this holds
    # ``{'victim_ids': [...]}`` on victim-PII reads so we can answer
    # "who saw which victims" without log-scraping.  Future routes can
    # add their own keys; readers must tolerate unknown shapes.
    extra: Mapped[dict[str, Any] | None] = mapped_column(_JSONB_OR_JSON, nullable=True)

    __table_args__ = (
        # Composite index for the "audit recent --user X --since 7d"
        # CLI query — the most common admin lookup.  Single-column
        # indexes on each column individually still cover ad-hoc
        # queries on just one dimension.
        Index("ix_audit_log_actor_timestamp", "actor_subject", "timestamp"),
    )

    def __repr__(self) -> str:
        actor = self.actor_subject or "anon"
        return (
            f"<AuditLog({self.timestamp.isoformat() if self.timestamp else '?'} "
            f"{actor} {self.method} {self.path} → {self.status_code})>"
        )
