import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import {
  Activity,
  CalendarClock,
  FileSearch,
  GitBranch,
  Layers,
  Package,
  Search,
  Shapes,
  Target,
  Trash2,
  TrendingUp,
  UserCheck,
  Users,
} from "lucide-react";
import { toast } from "sonner";
import {
  Bar,
  BarChart,
  CartesianGrid,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

import {
  useCampaign,
  useCampaignActors,
  useCampaignFamilies,
  useCampaignIndicators,
  useCampaignKits,
  useCampaignStats,
  useCampaignVictims,
  useCampaignYaraRules,
  useDeleteCampaign,
  useUpdateCampaign,
} from "@/hooks/use-campaigns";
import { EditableDescription } from "@/components/shared/editable-description";
import { EditableText } from "@/components/shared/editable-text";
import { KitStatusBadge } from "@/components/shared/kit-status-badge";
import { IocTypeBadge } from "@/components/shared/ioc-type-badge";
import { Pagination } from "@/components/shared/pagination";
import { PageLoading, TableLoading } from "@/components/shared/loading";
import { SuggestedKitsPanel } from "@/components/shared/suggested-kits-panel";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

const KITS_PAGE_SIZE = 25;
const INDICATORS_PAGE_SIZE = 25;
const VICTIMS_PAGE_SIZE = 25;

function formatDateOnly(iso: string | null | undefined): string {
  if (!iso) return "—";
  return new Date(iso).toLocaleDateString();
}

// Pretty-print the VictimObservationSource enum from the API.  We
// keep the underscore-y backend enum on the wire and translate for
// the operator at render time only.
const SOURCE_LABEL: Record<string, string> = {
  oauth_state: "OAuth state",
  oauth_login_hint: "OAuth login_hint",
  aitm_url_fragment: "AITM URL #fragment",
  eml_to: "EML To:",
  eml_cc: "EML Cc:",
  eml_bcc: "EML Bcc:",
  kit_content: "Kit content",
  other: "Other",
};

// ---------------------------------------------------------------------------
// Header
// ---------------------------------------------------------------------------

function CampaignHeader({
  id,
  name,
  targetBrand,
  autoGenerated,
  onUpdate,
  onDelete,
  isUpdating,
  isDeleting,
}: {
  id: string;
  name: string;
  targetBrand: string | null | undefined;
  autoGenerated: boolean | undefined;
  onUpdate: (next: string) => void;
  onDelete: () => void;
  isUpdating: boolean;
  isDeleting: boolean;
}) {
  return (
    <div className="flex items-start justify-between gap-4 flex-wrap">
      <div className="space-y-2 min-w-0">
        <div className="flex items-center gap-2 flex-wrap">
          <Target className="h-6 w-6 text-muted-foreground shrink-0" />
          <EditableText
            value={name}
            onSave={onUpdate}
            isPending={isUpdating}
            displayClassName="text-2xl font-bold tracking-tight"
            allowEmpty={false}
            placeholder="Campaign name"
          />
          {targetBrand && (
            <Badge variant="secondary" className="text-xs">
              {targetBrand}
            </Badge>
          )}
          {autoGenerated && (
            <Badge variant="outline" className="text-xs">
              auto-generated
            </Badge>
          )}
        </div>
        <p className="text-xs text-muted-foreground font-mono">{id}</p>
      </div>
      <Button
        variant="destructive"
        size="sm"
        onClick={onDelete}
        disabled={isDeleting}
      >
        <Trash2 className="h-4 w-4 mr-1" />
        {isDeleting ? "Deleting…" : "Delete"}
      </Button>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Overview tab
// ---------------------------------------------------------------------------

function StatCard({
  icon: Icon,
  label,
  value,
  hint,
}: {
  icon: typeof Users;
  label: string;
  value: number | string;
  hint?: string;
}) {
  return (
    <Card>
      <CardContent className="p-4">
        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          <Icon className="h-3.5 w-3.5" />
          {label}
        </div>
        <div className="text-2xl font-bold mt-1">{value}</div>
        {hint && (
          <div className="text-[10px] text-muted-foreground mt-0.5">{hint}</div>
        )}
      </CardContent>
    </Card>
  );
}

function OverviewTab({ id }: { id: string }) {
  const { data: stats, isLoading } = useCampaignStats(id);

  if (isLoading || !stats) return <TableLoading />;

  return (
    <div className="space-y-4">
      <div className="grid gap-3 grid-cols-2 md:grid-cols-5">
        <StatCard icon={Package} label="Kits" value={stats.kit_count} />
        <StatCard
          icon={UserCheck}
          label="Victims"
          value={stats.victim_count}
          hint="distinct, monitored"
        />
        <StatCard
          icon={Users}
          label="Curated actors"
          value={stats.actor_count}
        />
        <StatCard icon={Layers} label="Families" value={stats.family_count} />
        <StatCard
          icon={Search}
          label="Indicators"
          value={stats.indicator_count}
        />
      </div>

      <Card>
        <CardContent className="grid gap-4 p-4 md:grid-cols-2">
          <div>
            <span className="text-xs text-muted-foreground flex items-center gap-1">
              <CalendarClock className="h-3 w-3" />
              First seen (computed from kits)
            </span>
            <p className="text-sm mt-1">
              {formatDateOnly(stats.first_seen_computed)}
            </p>
          </div>
          <div>
            <span className="text-xs text-muted-foreground flex items-center gap-1">
              <CalendarClock className="h-3 w-3" />
              Last seen (computed from kits)
            </span>
            <p className="text-sm mt-1">
              {formatDateOnly(stats.last_seen_computed)}
            </p>
          </div>
        </CardContent>
      </Card>

      {/* Activity-over-time bar chart */}
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-medium flex items-center gap-2">
            <TrendingUp className="h-4 w-4" />
            Activity over time
          </CardTitle>
        </CardHeader>
        <CardContent>
          {stats.timeline.length === 0 ? (
            <p className="text-sm text-muted-foreground py-4">
              No kit activity recorded yet.
            </p>
          ) : (
            <div className="h-48">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={stats.timeline}>
                  <CartesianGrid
                    strokeDasharray="3 3"
                    className="stroke-muted"
                  />
                  <XAxis
                    dataKey="month"
                    fontSize={11}
                    className="text-muted-foreground"
                  />
                  <YAxis
                    fontSize={11}
                    allowDecimals={false}
                    className="text-muted-foreground"
                  />
                  <Tooltip
                    cursor={{ fill: "hsl(var(--muted))", opacity: 0.3 }}
                    contentStyle={{
                      background: "hsl(var(--popover))",
                      border: "1px solid hsl(var(--border))",
                      fontSize: 12,
                    }}
                  />
                  <Bar
                    dataKey="count"
                    fill="hsl(var(--primary))"
                    className="fill-emerald-500"
                  />
                </BarChart>
              </ResponsiveContainer>
            </div>
          )}
        </CardContent>
      </Card>

      <div className="grid gap-4 md:grid-cols-2">
        {/* Top victims */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <UserCheck className="h-4 w-4" />
              Top victims
            </CardTitle>
          </CardHeader>
          <CardContent>
            {stats.top_victims.length === 0 ? (
              <p className="text-sm text-muted-foreground">
                No monitored victims observed in this campaign yet.
              </p>
            ) : (
              <DistributionBars
                items={stats.top_victims.map((v) => ({
                  label: v.display_name || v.email,
                  count: v.count,
                  href: `/phishprint/victims/${v.victim_id}`,
                }))}
              />
            )}
          </CardContent>
        </Card>

        {/* Victim source-channel breakdown */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <Shapes className="h-4 w-4" />
              Hit channels
            </CardTitle>
          </CardHeader>
          <CardContent>
            {stats.victim_source_breakdown.length === 0 ? (
              <p className="text-sm text-muted-foreground">
                No victim observation channels recorded yet.
              </p>
            ) : (
              <DistributionBars
                items={stats.victim_source_breakdown.map((s) => ({
                  label: SOURCE_LABEL[s.source] ?? s.source,
                  count: s.count,
                  href: undefined,
                }))}
              />
            )}
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        {/* Top deploying actors */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <Users className="h-4 w-4" />
              Top deploying actors
            </CardTitle>
          </CardHeader>
          <CardContent>
            {stats.top_actors.length === 0 ? (
              <p className="text-sm text-muted-foreground">
                No actor attributions on this campaign's kits yet.
              </p>
            ) : (
              <DistributionBars
                items={stats.top_actors.map((a) => ({
                  label: a.actor_name,
                  count: a.count,
                  href: `/actors/${a.actor_id}`,
                }))}
              />
            )}
          </CardContent>
        </Card>

        {/* Top families */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <Layers className="h-4 w-4" />
              Top families
            </CardTitle>
          </CardHeader>
          <CardContent>
            {stats.top_families.length === 0 ? (
              <p className="text-sm text-muted-foreground">
                No family attributions on this campaign's kits yet.
              </p>
            ) : (
              <DistributionBars
                items={stats.top_families.map((f) => ({
                  label: f.family_name,
                  count: f.count,
                  href: `/families/${f.family_id}`,
                }))}
              />
            )}
          </CardContent>
        </Card>
      </div>

      {/* Top YARA rules */}
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-medium flex items-center gap-2">
            <FileSearch className="h-4 w-4" />
            Top YARA rules
          </CardTitle>
        </CardHeader>
        <CardContent>
          {stats.top_yara_rules.length === 0 ? (
            <p className="text-sm text-muted-foreground">
              No YARA matches across this campaign's kits.
            </p>
          ) : (
            <DistributionBars
              items={stats.top_yara_rules.map((r) => ({
                label: r.rule,
                count: r.count,
                href: `/kits?yara_rule=${encodeURIComponent(r.rule)}`,
              }))}
            />
          )}
        </CardContent>
      </Card>

      {/* Top indicators panel */}
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-medium flex items-center gap-2">
            <Search className="h-4 w-4" />
            Top indicators
          </CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          {stats.top_indicators.length === 0 ? (
            <p className="text-sm text-muted-foreground p-4">
              No indicators across this campaign's kits yet.
            </p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Type</TableHead>
                  <TableHead>Value</TableHead>
                  <TableHead className="text-right">Count</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {stats.top_indicators.map((ind, idx) => (
                  <TableRow key={`${ind.type}-${ind.value}-${idx}`}>
                    <TableCell>
                      <IocTypeBadge type={ind.type as never} />
                    </TableCell>
                    <TableCell className="font-mono text-xs max-w-md truncate">
                      {ind.value}
                    </TableCell>
                    <TableCell className="text-right font-mono">
                      {ind.count}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

// Same DistributionBars impl as actor / family detail.  Once the
// fourth copy lands we should promote it; meanwhile the component is
// small enough that drift cost is low.
function DistributionBars({
  items,
}: {
  items: { label: string; count: number; href: string | undefined }[];
}) {
  const max = Math.max(...items.map((i) => i.count));
  return (
    <div className="space-y-2">
      {items.map((it) => {
        const labelEl = (
          <span className="truncate text-sm" title={it.label}>
            {it.label}
          </span>
        );
        return (
          <div key={it.label} className="flex items-center gap-3 text-sm">
            <div className="w-32 shrink-0 text-muted-foreground hover:text-foreground">
              {it.href ? (
                <Link to={it.href} className="hover:underline">
                  {labelEl}
                </Link>
              ) : (
                labelEl
              )}
            </div>
            <div className="flex-1 h-2 rounded-full bg-muted overflow-hidden">
              <div
                className="h-full bg-emerald-500/80 transition-all"
                style={{ width: `${(it.count / max) * 100}%` }}
              />
            </div>
            <span className="w-10 text-right font-mono text-xs">
              {it.count}
            </span>
          </div>
        );
      })}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Identity tab — operator-editable description + target brand + dates
// ---------------------------------------------------------------------------

function IdentityTab({
  id,
  description,
  targetBrand,
  startDate,
  endDate,
  onUpdate,
  isUpdating,
}: {
  id: string;
  description: string | null | undefined;
  targetBrand: string | null | undefined;
  startDate: string | null | undefined;
  endDate: string | null | undefined;
  onUpdate: (data: Record<string, unknown>) => void;
  isUpdating: boolean;
}) {
  return (
    <div className="space-y-4">
      <EditableDescription
        value={description}
        onSave={(d) => onUpdate({ description: d })}
        isPending={isUpdating}
      />

      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-sm font-medium">Campaign metadata</CardTitle>
        </CardHeader>
        <CardContent className="grid gap-4 md:grid-cols-3">
          <div>
            <span className="text-xs text-muted-foreground">Target brand</span>
            <div className="mt-1">
              <EditableText
                value={targetBrand ?? ""}
                onSave={(v) => onUpdate({ target_brand: v || null })}
                isPending={isUpdating}
                placeholder="Microsoft, Coinbase, …"
                allowEmpty
              />
            </div>
          </div>
          <div>
            <span className="text-xs text-muted-foreground">Start date</span>
            <div className="mt-1">
              <EditableText
                value={startDate ?? ""}
                onSave={(v) => onUpdate({ start_date: v || null })}
                isPending={isUpdating}
                placeholder="2026-01-15"
                allowEmpty
              />
            </div>
          </div>
          <div>
            <span className="text-xs text-muted-foreground">End date</span>
            <div className="mt-1">
              <EditableText
                value={endDate ?? ""}
                onSave={(v) => onUpdate({ end_date: v || null })}
                isPending={isUpdating}
                placeholder="2026-03-22 or blank if active"
                allowEmpty
              />
            </div>
          </div>
        </CardContent>
      </Card>

      <SuggestedKitsPanel entityType="campaign" entityId={id} entityName="" />
    </div>
  );
}

// ---------------------------------------------------------------------------
// Kits tab
// ---------------------------------------------------------------------------

function KitsTab({ id }: { id: string }) {
  const [offset, setOffset] = useState(0);
  const { data, isLoading } = useCampaignKits(id, {
    offset,
    limit: KITS_PAGE_SIZE,
  });

  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle className="text-sm font-medium">
          Kits attributed to this campaign
          {data && (
            <span className="text-xs text-muted-foreground font-normal ml-2">
              ({data.total})
            </span>
          )}
        </CardTitle>
      </CardHeader>
      <CardContent className="p-0">
        {isLoading ? (
          <div className="p-4">
            <TableLoading />
          </div>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Status</TableHead>
                <TableHead>Source URL</TableHead>
                <TableHead>SHA256</TableHead>
                <TableHead>Created</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {(data?.items ?? []).map((kit) => (
                <TableRow key={kit.id} className="cursor-pointer hover:bg-muted/40">
                  <TableCell>
                    <KitStatusBadge status={kit.status} />
                  </TableCell>
                  <TableCell className="font-mono text-xs max-w-md truncate">
                    <Link to={`/kits/${kit.id}`} className="hover:underline">
                      {kit.source_url}
                    </Link>
                  </TableCell>
                  <TableCell className="font-mono text-xs text-muted-foreground">
                    {kit.sha256?.slice(0, 12) ?? "—"}
                  </TableCell>
                  <TableCell className="text-xs text-muted-foreground whitespace-nowrap">
                    {new Date(kit.created_at).toLocaleString()}
                  </TableCell>
                </TableRow>
              ))}
              {data && data.items.length === 0 && (
                <TableRow>
                  <TableCell
                    colSpan={4}
                    className="text-center text-muted-foreground py-8"
                  >
                    No kits attributed to this campaign yet.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        )}
      </CardContent>
      {data && data.total > KITS_PAGE_SIZE && (
        <div className="p-3">
          <Pagination
            offset={offset}
            limit={KITS_PAGE_SIZE}
            total={data.total}
            onOffsetChange={setOffset}
          />
        </div>
      )}
    </Card>
  );
}

// ---------------------------------------------------------------------------
// Victims tab — PhishPrint integration
// ---------------------------------------------------------------------------

function VictimsTab({ id }: { id: string }) {
  const [offset, setOffset] = useState(0);
  const { data, isLoading } = useCampaignVictims(
    id, offset, VICTIMS_PAGE_SIZE,
  );

  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle className="text-sm font-medium">
          Monitored victims observed in this campaign
          {data && (
            <span className="text-xs text-muted-foreground font-normal ml-2">
              ({data.total})
            </span>
          )}
        </CardTitle>
      </CardHeader>
      <CardContent className="p-0">
        {isLoading ? (
          <div className="p-4">
            <TableLoading />
          </div>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Email</TableHead>
                <TableHead>Display name</TableHead>
                <TableHead>Type</TableHead>
                <TableHead>Domain</TableHead>
                <TableHead>Last seen</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {(data?.items ?? []).map((v) => (
                <TableRow key={v.id} className="cursor-pointer hover:bg-muted/40">
                  <TableCell className="font-mono text-xs">
                    <Link
                      to={`/phishprint/victims/${v.id}`}
                      className="hover:underline"
                    >
                      {v.email}
                    </Link>
                  </TableCell>
                  <TableCell className="text-sm">
                    {v.display_name ?? "—"}
                  </TableCell>
                  <TableCell>
                    <Badge variant="outline" className="text-xs">
                      {v.type}
                    </Badge>
                  </TableCell>
                  <TableCell className="font-mono text-xs text-muted-foreground">
                    {v.domain}
                  </TableCell>
                  <TableCell className="text-xs text-muted-foreground whitespace-nowrap">
                    {v.last_seen
                      ? new Date(v.last_seen).toLocaleString()
                      : "—"}
                  </TableCell>
                </TableRow>
              ))}
              {data && data.items.length === 0 && (
                <TableRow>
                  <TableCell
                    colSpan={5}
                    className="text-center text-muted-foreground py-8"
                  >
                    No monitored victims observed in this campaign yet.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        )}
      </CardContent>
      {data && data.total > VICTIMS_PAGE_SIZE && (
        <div className="p-3">
          <Pagination
            offset={offset}
            limit={VICTIMS_PAGE_SIZE}
            total={data.total}
            onOffsetChange={setOffset}
          />
        </div>
      )}
    </Card>
  );
}

// ---------------------------------------------------------------------------
// Indicators tab
// ---------------------------------------------------------------------------

function IndicatorsTab({ id }: { id: string }) {
  const [offset, setOffset] = useState(0);
  const { data, isLoading } = useCampaignIndicators(
    id, offset, INDICATORS_PAGE_SIZE,
  );

  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle className="text-sm font-medium">
          Indicators across campaign kits
          {data && (
            <span className="text-xs text-muted-foreground font-normal ml-2">
              ({data.total})
            </span>
          )}
        </CardTitle>
      </CardHeader>
      <CardContent className="p-0">
        {isLoading ? (
          <div className="p-4">
            <TableLoading />
          </div>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Type</TableHead>
                <TableHead>Value</TableHead>
                <TableHead>Confidence</TableHead>
                <TableHead>Created</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {(data?.items ?? []).map((ind) => (
                <TableRow key={ind.id}>
                  <TableCell>
                    <IocTypeBadge type={ind.type as never} />
                  </TableCell>
                  <TableCell className="font-mono text-xs max-w-md truncate">
                    {ind.value}
                  </TableCell>
                  <TableCell className="text-xs">{ind.confidence}</TableCell>
                  <TableCell className="text-xs text-muted-foreground whitespace-nowrap">
                    {new Date(ind.created_at).toLocaleString()}
                  </TableCell>
                </TableRow>
              ))}
              {data && data.items.length === 0 && (
                <TableRow>
                  <TableCell
                    colSpan={4}
                    className="text-center text-muted-foreground py-8"
                  >
                    No indicators across this campaign's kits yet.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        )}
      </CardContent>
      {data && data.total > INDICATORS_PAGE_SIZE && (
        <div className="p-3">
          <Pagination
            offset={offset}
            limit={INDICATORS_PAGE_SIZE}
            total={data.total}
            onOffsetChange={setOffset}
          />
        </div>
      )}
    </Card>
  );
}

// ---------------------------------------------------------------------------
// YARA tab
// ---------------------------------------------------------------------------

function YaraTab({ id }: { id: string }) {
  const { data, isLoading } = useCampaignYaraRules(id);
  if (isLoading) return <TableLoading />;
  if (!data || data.length === 0) {
    return (
      <p className="text-sm text-muted-foreground p-4">
        No YARA rule matches across this campaign's kits yet.
      </p>
    );
  }
  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle className="text-sm font-medium">
          YARA rules anchoring this campaign
          <span className="text-xs text-muted-foreground font-normal ml-2">
            ({data.length})
          </span>
        </CardTitle>
      </CardHeader>
      <CardContent className="p-0">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Rule</TableHead>
              <TableHead className="text-right">Kits matched</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {data.map((r) => (
              <TableRow key={r.rule}>
                <TableCell className="font-mono text-xs">
                  <Link
                    to={`/kits?yara_rule=${encodeURIComponent(r.rule)}`}
                    className="hover:underline"
                  >
                    {r.rule}
                  </Link>
                </TableCell>
                <TableCell className="text-right font-mono">{r.count}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  );
}

// ---------------------------------------------------------------------------
// Actors + Families tabs
// ---------------------------------------------------------------------------

function ActorsTab({ id }: { id: string }) {
  const { data, isLoading } = useCampaignActors(id);
  if (isLoading) return <TableLoading />;
  if (!data || data.length === 0) {
    return (
      <p className="text-sm text-muted-foreground p-4">
        No actors curated as members of this campaign.
      </p>
    );
  }
  return (
    <Card>
      <CardContent className="p-4 flex flex-wrap gap-2">
        {data.map((a) => (
          <Link key={a.id} to={`/actors/${a.id}`}>
            <Badge
              variant="outline"
              className="cursor-pointer hover:bg-muted text-sm py-1"
            >
              <Users className="h-3 w-3 mr-1" />
              {a.name}
            </Badge>
          </Link>
        ))}
      </CardContent>
    </Card>
  );
}

function FamiliesTab({ id }: { id: string }) {
  const { data, isLoading } = useCampaignFamilies(id);
  if (isLoading) return <TableLoading />;
  if (!data || data.length === 0) {
    return (
      <p className="text-sm text-muted-foreground p-4">
        No families share kits with this campaign yet.
      </p>
    );
  }
  return (
    <Card>
      <CardContent className="p-4 flex flex-wrap gap-2">
        {data.map((f) => (
          <Link key={f.id} to={`/families/${f.id}`}>
            <Badge
              variant="outline"
              className="cursor-pointer hover:bg-muted text-sm py-1"
            >
              <GitBranch className="h-3 w-3 mr-1" />
              {f.name}
            </Badge>
          </Link>
        ))}
      </CardContent>
    </Card>
  );
}

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

export function CampaignDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { data: campaign, isLoading } = useCampaign(id!);
  const updateMutation = useUpdateCampaign();
  const deleteMutation = useDeleteCampaign();

  if (isLoading || !campaign || !id) return <PageLoading />;

  const handleUpdate = (data: Record<string, unknown>) => {
    updateMutation.mutate(
      { id, ...data },
      {
        onSuccess: () => toast.success("Saved"),
        onError: (err) => toast.error(err.message),
      },
    );
  };

  const handleDelete = () => {
    if (
      !window.confirm(
        `Delete campaign "${campaign.name}"? Linked kits will be unlinked but not deleted.`,
      )
    )
      return;
    deleteMutation.mutate(id, { onSuccess: () => navigate("/campaigns") });
  };

  return (
    <div className="space-y-6">
      <CampaignHeader
        id={id}
        name={campaign.name}
        targetBrand={campaign.target_brand}
        autoGenerated={campaign.auto_generated}
        onUpdate={(name) => handleUpdate({ name })}
        onDelete={handleDelete}
        isUpdating={updateMutation.isPending}
        isDeleting={deleteMutation.isPending}
      />

      <Tabs defaultValue="overview">
        <TabsList className="overflow-x-auto overflow-y-hidden">
          <TabsTrigger value="overview">
            <Activity className="h-3.5 w-3.5 mr-1.5" />
            Overview
          </TabsTrigger>
          <TabsTrigger value="identity">
            <Target className="h-3.5 w-3.5 mr-1.5" />
            Identity
          </TabsTrigger>
          <TabsTrigger value="kits">
            <Package className="h-3.5 w-3.5 mr-1.5" />
            Kits
          </TabsTrigger>
          <TabsTrigger value="victims">
            <UserCheck className="h-3.5 w-3.5 mr-1.5" />
            Victims
          </TabsTrigger>
          <TabsTrigger value="indicators">
            <Search className="h-3.5 w-3.5 mr-1.5" />
            Indicators
          </TabsTrigger>
          <TabsTrigger value="yara">
            <FileSearch className="h-3.5 w-3.5 mr-1.5" />
            YARA
          </TabsTrigger>
          <TabsTrigger value="actors">
            <Users className="h-3.5 w-3.5 mr-1.5" />
            Actors
          </TabsTrigger>
          <TabsTrigger value="families">
            <Layers className="h-3.5 w-3.5 mr-1.5" />
            Families
          </TabsTrigger>
        </TabsList>

        <TabsContent value="overview" className="mt-4">
          <OverviewTab id={id} />
        </TabsContent>
        <TabsContent value="identity" className="mt-4">
          <IdentityTab
            id={id}
            description={campaign.description}
            targetBrand={campaign.target_brand}
            startDate={campaign.start_date}
            endDate={campaign.end_date}
            onUpdate={handleUpdate}
            isUpdating={updateMutation.isPending}
          />
        </TabsContent>
        <TabsContent value="kits" className="mt-4">
          <KitsTab id={id} />
        </TabsContent>
        <TabsContent value="victims" className="mt-4">
          <VictimsTab id={id} />
        </TabsContent>
        <TabsContent value="indicators" className="mt-4">
          <IndicatorsTab id={id} />
        </TabsContent>
        <TabsContent value="yara" className="mt-4">
          <YaraTab id={id} />
        </TabsContent>
        <TabsContent value="actors" className="mt-4">
          <ActorsTab id={id} />
        </TabsContent>
        <TabsContent value="families" className="mt-4">
          <FamiliesTab id={id} />
        </TabsContent>
      </Tabs>
    </div>
  );
}
